version: '3.8'

services:
  app:
    build: .
    container_name: arBETrage
    volumes:
      - ./src:/src
    env_file: .env-NY
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydb

volumes:
  mongo_data:
