services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  airflow-init:
    image: apache/airflow:2.9.1-python3.9
    container_name: airflow-init
    depends_on:
      - mongo
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'dcDaNM_dOqByUUv34ulVH1sX6SXO-A_YY2Zl68chtKQ'
      PYTHONPATH: /opt/airflow/src
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./src/requirements.txt:/requirements.txt
    entrypoint: >
      bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
      "


  airflow-webserver:
    image: apache/airflow:2.9.1-python3.9
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-init
      - postgres
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
      AIRFLOW__WEBSERVER__SECRET_KEY: 'dcDaNM_dOqByUUv34ulVH1sX6SXO-A_YY2Zl68chtKQ'
      PYTHONPATH: /opt/airflow/src
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./src/requirements.txt:/requirements.txt
    command: >
      bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      airflow webserver
      "

  airflow-scheduler:
    image: apache/airflow:2.9.1-python3.9
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-init
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'dcDaNM_dOqByUUv34ulVH1sX6SXO-A_YY2Zl68chtKQ'
      PYTHONPATH: /opt/airflow/src
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./src/requirements.txt:/requirements.txt
    command: >
      bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      airflow scheduler
      "

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
